name: "Podcast Generator User"
author: "Russell"
description: "Generates a feed for a podcast from a yaml file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  emails:
     description: The commiter's email address
     required: true
     default: ${{ github.actor }}@localhost
  name:
      descirption: The commiter's name
      required: true
      default: ${{ github.actor }}
